# This is a basic workflow to help you get started with Actions

name: A

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "A"
  A:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: B
          #token: ${{ secrets.PERSONAL_TOKEN }}
