# This is a basic workflow to help you get started with Actions

name: HelloLarry

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: setter
        run: echo "::set-output name=out1::ps -ef"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "GITHUB_STEP_SUMMARY is $GITHUB_STEP_SUMMARY"
          echo "The prior output is ${{steps.setter.outputs.out1 }}"
          echo "## Terraform Plan Output"  >> $GITHUB_STEP_SUMMARY
          #echo "```"   >> $GITHUB_STEP_SUMMARY
          echo "${{steps.setter.outputs.out1 }}"  >> $GITHUB_STEP_SUMMARY
          #echo "```"   >> $GITHUB_STEP_SUMMARY
          tail $GITHUB_STEP_SUMMARY
